version: 2

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
  exclusions:
    paths:
      - "codegen/.*"
      - "gen/.*"

linters-settings:
  errcheck:
    check-type-assertions: true
