version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
  exclusions:
    paths:
      - "codegen/.*"
      - "gen/.*"
  settings:
    errcheck:
      check-type-assertions: true
